jobs:
  build:
    docker:
      - image: "cimg/python:3.6"
    steps:
      - checkout
      - aws-s3/copy:
          aws-access-key-id: AKIAVFAPNZ6QQ6NO5G4S
          aws-region: us-east-1
          aws-secret-access-key: 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
          from: JJ_Resume.pdf
          to: "s3://jj-resume.pdf"
orbs:
  aws-s3: circleci/aws-s3@1.0.15
version: 2.1
